spring:
  datasource:
    url: jdbc:mysql://mysql.selune.top:3306/gymsell?characterEncoding=utf-8&useSSL=false
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false